### ISSUE TITLE
Отзыв

### ISSUE THREAD

**Issue by grigoriyeltsov** [notdest/privod#1]
Добрый день! Хотел сказать вам огромное спасибо за отлично проделанную работу! Очень понравилась реализация, без ничего лишнего и главное возможность торговать через горячие клавиши. Если вас не затруднит, не могли бы вы более подробную инструкцию по установке записать, может быть в видео формате. Особенно интересует установка на фьючерсном контракте на нефть. Скажите, есть ли планы развивать проект? В общем заранее спасибо. Успехов!

**Comment by notdest** [comment]
Здравствуйте, хорошо, попробую описать подробнее. Пока планов развивать нету.

**Comment by notdest** [comment]
Расписал подробнее. Для торговли  одним фьючом без ведущей акции можно просто указать акцию, для которой нигде не открыт стакан котировок - иначе он будет её отображать, вычислять контанго на старте и тп. Саму таблицу можно просто поуже сделать, чтобы неиспользуемые столбцы не бросались в глаза

**Comment by grigoriyeltsov** [comment]
Большое спасибо!
